sudo: required
services:
  - docker

before_install:
  - docker build -t danielhasler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danielhasler/docker-react npm run test -- --coverage
